services:
    postgresql:
        container_name: strixhaven-db
        image: postgres:alpine
        ports:
            - 5434:5432
        environment:
            POSTGRES_DB: $DB_NAME
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
        restart: always