from .book_router import router as book_router
from .calendar_note_router import router as calendar_note_router
from .character_note_router import router as character_note_router
from .character_sheet_router import router as character_sheet_router
from .class_router import router as class_router
from .college_router import router as college_router
from .event_note_router import router as event_note_router
from .inventory_item_router import router as inventory_item_router
from .map_router import router as map_router
from .monster_router import router as monster_router
from .news_router import router as news_router
from .note_router import router as note_router
from .npc_router import router as npc_router
from .npc_note_router import router as npc_note_router
from .npc_reputation_router import router as npc_reputation_router
from .player_character_router import router as player_character_router
from .session_router import router as session_router
from .store_item_router import router as store_item_router
from .store_router import router as store_router
from .user_router import router as user_router